# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['appRun.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        "altgraph",
        "click",
        "Cython",
        "future",
        "lxml",
        "numpy",
        "opencv-python",
        "pefile",
        "pluginbase",
        "pyperclip",
        "PyQt5",
        "pyqt5-plugins",
        "PyQt5-Qt5",
        "PyQt5-sip",
        "pyqt5-tools",
        "python-docx",
        "python-dotenv",
        "pywin32-ctypes",
        "qt5-applications",
        "qt5-tools",
        "sqlite3",
        "cv2",
        "docx",
        "pandas",
        "requests",
        "Cryptodome",
        "Cryptodome.Cipher.AES",
        "Cryptodome.Random",
        "wmi",
        "WMI",
        "xlsxwriter",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.src,
    [],
    exclude_binaries=True,
    name='appRun',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['app.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='appRun',
)
